executable = condor_gen.sh
arguments = $(ClusterID) $(ProcId) $(CELL)
output = output/gen.$(ClusterId).$(CELL).out
error = error/gen.$(ClusterId).$(CELL).err
log = log/gen.$(ClusterId).log
+JobFlavour = "tomorrow"
request_memory = 12GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue CELL from seq 0 323 |
